### ISSUE TITLE
Obtención rápida de datos para comparativas por género.

### ISSUE THREAD

**Issue by manucabral** [manucabral/Codavi#1]
Implementar un _dataset_ que contenga la columna _'género'_ para la comparativa de masculinos y femeninos, este mismo tiene que ser analizado de forma rápida para la API.

https://github.com/manucabral/Codavi/blob/ce963a592da8ca5c1e8356a91db93497cb8322ba/api/main.py#L5

**Comment by erickjq10x** [comment]
encontre los datos necesarios, (https://datos.gob.ar/dataset/salud-vacunas-contra-covid-19-dosis-aplicadas-republica-argentina---registro-desagregado) acá estan los datos pesa 400mb

**Comment by GabrielCarames** [comment]
Se podría traer los datos tardios a un servidor aparte, almacenarlos localmente o en una base de datos, y luego que la página tome los datos ya "formateados" o limpios sin el tiempo de 80s.

**Comment by manucabral** [comment]
> Se podría traer los datos tardios a un servidor aparte, almacenarlos localmente o en una base de datos, y luego que la página tome los datos ya "formateados" o limpios sin el tiempo de 80s.

Voy a implementar tu idea y vemos su productividad.

**Comment by manucabral** [comment]
Encontre esta [página](https://www.argentina.gob.ar/salud/coronavirus-COVID-19/sala-situacion) de monitoreo de datos del Ministerio de Salud de la Nación que nos puede servir.

**Comment by manucabral** [comment]
> > Se podría traer los datos tardios a un servidor aparte, almacenarlos localmente o en una base de datos, y luego que la página tome los datos ya "formateados" o limpios sin el tiempo de 80s.
> 
> Voy a implementar tu idea y vemos su productividad.

Al final cree una base de datos donde progresivamente se irán metiendo o actualizando los datos tardíos de Codavi mientras que la API obtendrá la información de esa base de datos.
